# file generated by vcs-versioning
# don't change, don't track in version control
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = '1.6.2.dev798+gec1cfbe78.d20260415'
__version_tuple__ = version_tuple = (1, 6, 2, 'dev798', 'gec1cfbe78.d20260415')

__commit_id__ = commit_id = 'gec1cfbe78'
